name: ChatOps
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    
jobs:
  build:
    name: Update Date
    runs-on: ubuntu-latest
    steps:
    - name: update
      run: |
        echo OK
      if: startsWith(github.event.comment.body, 'date')
