name: ChatOps
on:
  issue_comment:
    types: [created, edited]
jobs:
  update_date:
    name: "Update Date"
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/date')
    runs-on: ubuntu-latest
    steps:
    - name: update
      run: |
        echo OK
