name: ChatOps

on:
  issue_comment:
    types: [created, edited]

jobs:
  update_date:
    name: "Update Date"
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/date') }}
    runs-on: ubuntu-latest
    steps:
      - name: get upstream branch
        id: upstreambranch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=branchname::$(curl -H "Authorization: token ${GITHUB_TOKEN}" ${{ github.event.issue.pull_request.url }} | jq '.head.ref' | sed 's/\"//g')"

      - name: Checkout upstream repo
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.upstreambranch.outputs.branchname }}
      
      - name: Update
        run: |
          date_now=$(date +'%Y/%m/%d')
          date_txt=$(echo $(cat update_dates/date_site.txt) | cut -c 1-10)
          echo ${{ steps.upstreambranch.outputs.branchname }}
          if [ $date_now != $date_txt ]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git fetch
            git checkout ${{ github.head_ref }}
            rm -f update_dates/date_site.txt
            echo $date_now >> update_dates/date_site.txt
            git add update_dates/date_site.txt
            git commit -m "update koushinbi (by github-actions)"
            git push
          fi
        env:
          TZ: 'Asia/Tokyo'
