name: ChatOps

on: issue_comment:

jobs:
  update_date:
    name: "Update Date"
    if: startsWith(github.event.comment.body, '/date')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on issue $NUMBER
