name: ChatOps

on:
  issue_comment:
    types: [created, edited]

jobs:
  update_date:
    name: "Update Date"
    if: startsWith(github.event.comment.body, '/date')
    runs-on: ubuntu-latest
    run: echo "OK"
