name: ChatOps

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  update_date:
    name: "Update Date"
    if: ${{ github.event.issue.pull_request }} && startsWith(github.event.comment.body, '/date')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout ${{ github.head_ref }}
