name: daily_update
on:
  schedule:
    # 日本時間で毎日 2 時 20 分に実行
    - cron: '20 17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4

      - name: Run script and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          python get_standing_and_join.py ${{secrets.ATCODER_PASSWORD}}
          git add points/points.txt
          if [[ -n $(git diff --name-only --cached) ]]; then
            date_now=$(date +'%Y/%m/%d')
            rm -f update_dates/date_site.txt
            rm -f update_dates/date_rank_data.txt
            echo $date_now >> update_dates/date_site.txt
            echo $date_now >> update_dates/date_rank_data.txt
            git add update_dates/date_site.txt
            git add update_dates/date_rank_data.txt
            git commit -m "daily update (point data)"
            git pull
            git push origin main
          fi
