name: daily_update
on:
  schedule:
    # 日本時間で毎日 15 時に実行
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests==2.31.0
          pip install beautifulsoup4==4.12.2

      - name: Run script and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          cd app
          mkdir raw_standings
          python get_standing_and_join.py ${{secrets.ATCODER_PASSWORD}}
          git add data/points/points.txt
          if [[ -n $(git diff --name-only --cached) ]]; then
            date_now=$(date +'%Y/%m/%d')
            date_yesterday=$(date +'%Y/%m/%d' --date '1 day ago')
            rm -f data/update_dates/date_site.txt
            rm -f data/update_dates/date_rank_data.txt
            echo $date_now >> data/update_dates/date_site.txt
            echo $date_yesterday >> data/update_dates/date_rank_data.txt
            git add data/update_dates/date_site.txt
            git add data/update_dates/date_rank_data.txt
            git commit -m "daily update (point data)"
            git pull
            git push origin main
          fi
        env:
          TZ: 'Asia/Tokyo'
