name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Check Date
        run: |
          date_now=$(date +'%Y/%m/%d')
          date_txt=$(echo $(cat app/data/update_dates/date_site.txt) | cut -c 1-10)
          echo $date_now
          echo $date_txt
          if [[ $date_now != $date_txt ]]; then exit 1; fi
        env:
          TZ: 'Asia/Tokyo'
