name: test_ci

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Date
        run: if [[ $(git log --date=iso --date=format:"%Y/%m/%d" --pretty=format:"%ad" -1) != $(cat update_dates/date_site.txt) ]]; then exit 1; fi
